version: '3'
services:
        web_server_02:
                build: ./
                image: nginx:1.12
                container_name: web_server_02
                ports:
                        - 80
                networks: 
                - vlan20
                

networks:
        vlan20:
                external:
                        name: vlan20
