version: '3'
services:
        proxy-reverso:
                
                image: nginx:1.12
                build: ./
                container_name: proxy-reverso
                ports:
                        - 8080:80
                networks:
                        - vlan20
                        - vlan10


networks:
        vlan20:
                external:
                        name: vlan20
        vlan10:
                external:
                        name: vlan10

